import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
// import './global.scss';
// import './assets/scss/variables.scss';

import './assets/scss/global.scss'
import Footer from './Components/Footer/page';
import ReduxProvider from './Components/ReduxProvider/ReduxProvider'

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <main className="main">{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
